language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly
    - hhvm

matrix:
    include:
        - php: 5.3.3
          dist: precise
          sudo: required
        - php: 5.3
          dist: precise
          sudo: required
        - php: 5.4
          dist: precise
          sudo: required
    fast_finish: true
    allow_failures:
        - php: nightly
        - php: hhvm

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

# faster builds on new travis setup not using sudo
sudo: false

before_install:
    # disable TLS for composer because openssl is disabled for PHP 5.3.3 on travis
    # see: https://blog.travis-ci.com/upcoming_ubuntu_11_10_migration/
    - if [[ $TRAVIS_PHP_VERSION = 5.3.3 ]]; then composer config -g -- disable-tls true; fi;
    - if [[ $TRAVIS_PHP_VERSION = 5.3.3 ]]; then composer config -g -- secure-http false; fi;

install:
    - composer self-update

before_script:
    - composer install --prefer-dist --no-interaction

script:
    - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - |
        wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover coverage.clover
