language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

# run build against 7.0 & hhvm but allow them to fail
matrix:
    fast_finish: true
    allow_failures:
        - php: 7.0
        - php: hhvm

# faster builds on new travis setup not using sudo
sudo: false

install:
    - composer self-update

before_script:
    - composer install --prefer-dist --no-interaction

script:
    - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - |
        wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover coverage.clover
