dist: xenial
os: linux
language: php

php:
    - 7.3
    - 7.4
    - nightly

jobs:
    include:
        - php: 7.2
          env: CS_FIXER=run
    fast_finish: true
    allow_failures:
        - php: nightly

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

install:
    - composer self-update

before_script:
    - composer install --prefer-dist --no-interaction -o

script:
    - php vendor/bin/simple-phpunit -v --coverage-clover=coverage.clover
    - if [ "$CS_FIXER" = "run" ]; then php vendor/bin/php-cs-fixer fix --verbose --dry-run ; fi;

after_script:
    - |
        wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover coverage.clover
